### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by mackrauss** [fastmail/authentication_milter#11]
In the README you say this is free software and link to the LICENSE file for further details, but this file is missing.

Could you add the file?

**Comment by marcbradshaw** [comment]
The licence file is generated by the Dist::Zilla build process. If you are building/installing from the github checkout then a 'dzil build' will do the right thing and create a directory with the release files including the licence.

**Comment by mackrauss** [comment]
Why not put it into the repo. The README has a link that then creates a Github 404. 

Kind of standard to have the LICENSE file in Github, no?
