### ISSUE TITLE
Use milter client with larger message body 

### ISSUE THREAD

**Issue by freddieleeman** [fastmail/authentication_milter#117]
Would it be possible to make the client work with a larger message body and avoid the error below?

```the message body is too big; its length must be less than 65536 bytes at /usr/local/share/perl/5.28.1/Mail/Milter/Authentication/Net/Milter.pm line 202.```

**Comment by marcbradshaw** [comment]
Hi @freddieleeman,

Can you check and see if the fix in the ChunkClientBody branch (mentioned above) fixes this.

Thanks.

**Comment by freddieleeman** [comment]
Are you kidding me?! Yes it does. You my friend, are a genius! Thank you.
