### ISSUE TITLE
When using ARC no Authentication-Results headers should be created

### ISSUE THREAD

**Issue by gizahNL** [fastmail/authentication_milter#126]
The spec states that these headers should not be added, as they're likely to be removed by downstream MTA's.

I might've missed something, but I could not find any documented way of preventing the generation of these headers.

**Comment by marcbradshaw** [comment]
Hi, If I understand correctly, you want to generate the ARC-Authentication-Results header but not the Authentication-Results header?
No, it's currently not possible to do this as the ARC sealing code uses the added Authentication-Results to generate it's ARC Seal and associated AAR headers.
