### ISSUE TITLE
auth milter's x-bits= tag causing fail in DKIM header extension in Thunderbird?

### ISSUE THREAD

**Issue by pgnd** [fastmail/authentication_milter#144]
@marcbradshaw 

fastmail.com's AR headers -- generated by authentication_milter -- appear to cause problems for a Thunderbird extension, "DKIM Verifier".  due to (?) the presence of 'x-bits' tag.

not clear to me where the cause of the problem lies ... with auth_milter, FM's config, of with the extension.
headers gen'd by gmail do not seem to cause the same issue.

could you spare a look at the issue report here,

 https://github.com/lieser/dkim_verifier/issues/384

and comment?

thx o/

**Comment by marcbradshaw** [comment]
I have commented on the issue, thanks for letting me know.

**Comment by pgnd** [comment]
thanks!
