### ISSUE TITLE
fyi, Net::IDN::Encode prereq build fail, re: `utf8_flags` usage, on Fedora 40+; patch/PR submitted, not merged, @ upstream

### ISSUE THREAD

**Issue by pgnd** [fastmail/authentication_milter#149]
fyi,

on the way to a clean perl/cpanm build of FM Auth Milter,
```
cpanm Mail::Milter::Authentication
```

module "Net::IDN::Encode" is required

on Fedora 40, the Net::IDN::Encode build fails, causing the FMAM milter build to fail
```
	cpanm Mail::Milter::Authentication
		...
		--> Working on Net::IDN::Encode
		Fetching http://www.cpan.org/authors/id/C/CF/CFAERBER/Net-IDN-Encode-2.500.tar.gz ... OK
		Configuring Net-IDN-Encode-2.500 ... OK
		==> Found dependencies: Test::NoWarnings
		--> Working on Test::NoWarnings
		Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Test-NoWarnings-1.06.tar.gz ... OK
		Configuring Test-NoWarnings-1.06 ... OK
		Building and testing Test-NoWarnings-1.06 ... OK
		Successfully installed Test-NoWarnings-1.06
!!!		Building and testing Net-IDN-Encode-2.500 ... FAIL
		! Installing Net::IDN::Encode failed. See /builddir/.cpanm/work/1706973715.284/build.log for details. Retry with --force to force install it.
		1 distribution installed
```

it's a known issue.

a bug's been opened, with a patch submitted,

	#149108: [PATCH] use uvchr_to_utf8_flags instead of uvuni_to_utf8_flags (which is removed in perl 5.38.0)
	https://rt.cpan.org/Ticket/Display.html?id=149108

also, a PR,

	use uvchr_to_utf8_flags instead of uvuni_to_utf8_flags (which is remo…
	https://github.com/cfaerber/Net-IDN-Encode/pull/11

maintainer's been non-responsive to either, to date.

fwiw, the patch provided,

	https://src.fedoraproject.org/rpms/perl-Net-IDN-Encode/raw/rawhide/f/Net-IDN-Encode-2.500-use_uvchr_to_utf8_flags_instead_of_uvuni_to_utf8_flags.patch

applies ok to Net::IDN::Encode source, fixes the issue, and gets to a successful FMAM build/install

<strike>(unless building in a root-less mock container, then Mail::SPF needs its doc'd "--install_path sbin=..." workaround)</strike>
_( --> fixed in_
```
	grep \$VERSION /usr/local/share/perl5/5.38/Mail/SPF.pm
		our $VERSION = '3.20240205'; # VERSION
```
_)_

**Comment by marcbradshaw** [comment]
Thanks for the info
