### ISSUE TITLE
unique AuthServID for auth milter instance?

### ISSUE THREAD

**Issue by pgd151** [fastmail/authentication_milter#15]
The auth-milter AuthServID Class appears to exist,

  https://metacpan.org/pod/Mail::AuthenticationResults::Header::AuthServID

How do you specify/config AuthServID for an auth-milter instance, so that the header is added as:

	Authentication-Results: instance-name.mx.example.net;

instead of, as currently

	Authentication-Results: mx.example.net;

?

Other milters' examples include:

(1) clamav-milter

with config,

	ReportHostname clamav-milter.mx.example.net

header's added as

	X-Virus-Scanned: clamav-milter 0.101.0 at clamav-milter.mx.example.net

(2) opendkim

with config

	AuthservIDWithJobId   yes
	AuthservID            opendkim.mx.example.net

header's added as

	DKIM-Filter: OpenDKIM Filter v2.7.5 some.domain.com w8OEBfva024786
	Authentication-Results: opendkim.mx.example.net/42JmNK1pJ4z12wc; ...

(3) opendmarc

with config

	AuthservIDWithJobID true
	AuthservID opendmarc.mx.example.net

header's added as

	DMARC-Filter: OpenDMARC Filter v1.4.0 mx.example.net 42JmNK1pJ4z12wc
	Authentication-Results: opendmarc.mx.example.net/42JmNK1pJ4z12wc; ...

**Comment by marcbradshaw** [comment]
When running in milter mode this is set by the calling MTA.
When running in SMTP mode this is set in the config as server_name in the smtp section.
