### ISSUE TITLE
Trouble installing crypt-curve25519 and CryptX on ubuntu 22.04

### ISSUE THREAD

**Issue by AgyarJanos** [fastmail/authentication_milter#150]
dependency issues

**Comment by marcbradshaw** [comment]
Do you have any details of the install failure?

**Comment by AgyarJanos** [comment]
Definitely should have. Sorry--I uninstalled and did a lot of other stuff.

I'll try again later & attach/send details; tomorrow if possible. I'd actually had to mess with another issue before I even got that far. So I'll give info on both.

Feb 15, 2024 5:09:58 PM Marc Bradshaw ***@***.***>:
