### ISSUE TITLE
Unknown "method" POD directive in Mail::Milter::Authentication(3pm)

### ISSUE THREAD

**Issue by rfc1036** [fastmail/authentication_milter#152]
A large part of the man page is missing because the POD document is invalid:

```
POD ERRORS
       Hey! The above document had some coding errors, which are explained
       below:

       Around line 75:
           Unknown directive: =method
```

**Comment by marcbradshaw** [comment]
This is not a bug the package used Pod Weaver, these directives are translated into the relevant valid POD directives during the build process.
Running a 'dzil build' and using the resulting build result should fix the errors.
