### ISSUE TITLE
cpan -i Mail::Milter::Authentication (OpenBSD)

### ISSUE THREAD

**Issue by patch-work** [fastmail/authentication_milter#157]
Installation failure.

> cpan -i Mail::Milter::Authentication

[mail_milter_authentication_log.txt](https://github.com/fastmail/authentication_milter/files/15337950/mail_milter_authentication_log.txt)

This explains why OpenBSD's package is stuck at 2016.

**Comment by patch-work** [comment]
The package maintainer is Giovanni Bechis
https://github.com/bigio?tab=repositories

**Comment by hdatma** [comment]
Bump.

**Comment by marcbradshaw** [comment]
Reproduced the test issues on an OpenBSD VM and will investigate, but can't guarantee a timescale on this one.

**Comment by patch-work** [comment]
2024-2016=8

**Comment by marcbradshaw** [comment]
Fixed in 3.20240618

```
openbsd# cpanm ./Mail-Milter-Authentication-3.20240618.tar.gz
--> Working on ./Mail-Milter-Authentication-3.20240618.tar.gz
Fetching file:///root/Mail-Milter-Authentication-3.20240618.tar.gz ... OK
Configuring Mail-Milter-Authentication-3.20240618 ... OK
Building and testing Mail-Milter-Authentication-3.20240618 ... OK
Successfully installed Mail-Milter-Authentication-3.20240618
1 distribution installed
openbsd#
```

**Comment by patch-work** [comment]
It compiles. 

The tests succeed except for the following:

```
t/03-func-milter.t .................................. ok
SMTP Send expected "250" received "421 4.3.2 Pipeline limit reached" when sending "RSET"
```

**Comment by marcbradshaw** [comment]
the test is making sure the condition throwing the warning is handled correctly, so the warning is expected and can be ignored.
