### ISSUE TITLE
Issues with dependencies on Debian 12 

### ISSUE THREAD

**Issue by amaclach** [fastmail/authentication_milter#160]
I haven't tried any other distros but I'm really having issues with dependencies.
Some I can get from CPAN, some I have to get as packages from the distro, and one or two I just can't get to install at all (fail on CPAN, not available from the distro)
What would be great would be for a package containing all the dependencies in a .deb package.
I really want to be able to get this to work....

**Comment by marcbradshaw** [comment]
Having everything in a .deb would be tricky as there could be issues with CPAN modules in that deb conflicting with system packages, depending on how it was packaged. It would surely be against the debian package style in that case.
The way to go could be docker, there is a very old image somewhere but it hasn't been updated for a number of years.
It wouldn't be something I could devote enough time to, but would also love to see as it would make installation much easier.

**Comment by amaclach** [comment]
Is there a full list of dependencies for the milter?
That way we can favor pre-packaged modules?
Are you aware of any apt repositories for perl modules?

CPAN can be a bit hit and miss, and it's super mega slow...

**Comment by birtalevente** [comment]
FWIW I built succesfully on debian12
It's pretty simple:

Clean install, without X

#apt update; apt upgrade
#apt install make gcc libssl-dev zlib1g zlib1g-dev libxml2-dev
#cpan install App::cpanminus
#cpanm Mail::Milter::Authentication

Take some time, but built with success.

good luck!

**Comment by amaclach** [comment]
Thanks.
Maybe I’ll give it another go when I have some spare time.
