### ISSUE TITLE
What does "Policy overriden using trusted ARC chain" mean

### ISSUE THREAD

**Issue by vicatcu** [fastmail/authentication_milter#24]
I received a DMARC email from fastmail saying:

2 records.
0 passed.
2 failed.

I looked at the attached XML and saw a comment "Policy overriden using trusted ARC chain" which led me to this repository. Please can you advise if I need to take further action?

Is this something I need to fix about my DKIM / DMARC records?

**Comment by freddieleeman** [comment]
No, you do not need to fix anything. This means the message was forwarded causing both DKIM and SPF to fail, but the message had a trusted ARC chain that caused the message to be accepted anyway. More about ARC and email security can be found [here](https://en.wikipedia.org/wiki/Authenticated_Received_Chain) and [here](https://www.uriports.com/blog/email-security-explained/).
