### ISSUE TITLE
Makefile.PL missing

### ISSUE THREAD

**Issue by freddieleeman** [fastmail/authentication_milter#31]
Installation from source instructions mention `Makefile.PL` but there is no file with that name.

**Comment by marcbradshaw** [comment]
The Readme is misleading here, it depends which 'source' you are building from.

The git checkout does not have a Makefile.PL as it uses Dist::Zilla, this builds the Perl source including the Makefile.PL

I'll update the README to be clearer.

Thanks.

**Comment by Sailfish33** [comment]
Please unsubscribe me from your mailing list
