### ISSUE TITLE
Can't call method "set" on an undefined value at Authentication/Metric.pm line 50.

### ISSUE THREAD

**Issue by freddieleeman** [fastmail/authentication_milter#45]
Building with cpanm results in the following error:

`Can't call method "set" on an undefined value at /usr/local/share/perl/5.28.1/Mail/Milter/Authentication/Metric.pm line 50.
        ...propagated at /usr/local/share/perl/5.28.1/Mail/Milter/Authentication.pm line 774.
`

**Comment by freddieleeman** [comment]
Not only with Buster, but also with Bullseye (perl 5.30):

`Can't call method "set" on an undefined value at /usr/local/share/perl/5.30.0/Mail/Milter/Authentication/Metric.pm line 50.
        ...propagated at /usr/local/share/perl/5.30.0/Mail/Milter/Authentication.pm line 774.
`

**Comment by marcbradshaw** [comment]
I see the problem, the prometheus object is only created if a metric_port or metric_connection are defined, but later the code which sets up versioning metrics assumes there will always be a metrics object.
Will be fixed in next release.

**Comment by freddieleeman** [comment]
Fixed in latest build!
